### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by refractored** [vincss/mcsleepingserverstarter#127]
The server leaves an error when using older versions like 1.8 or 1.12 to start the server.
Error:
```
PartialReadError: Read error for undefined : undefined
    at new ExtendableError (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/utils.js:63:13)
    at new PartialReadError (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/utils.js:70:5)
    at Object.readBool [as bool] (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/datatypes/utils.js:133:41)
    at eval (eval at compile (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/compiler.js:258:12), <anonymous>:501:29)
    at Object.packet_login_start (eval at compile (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/compiler.js:258:12), <anonymous>:526:9)
    at eval (eval at compile (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/compiler.js:258:12), <anonymous>:588:62)
    at packet (eval at compile (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/compiler.js:258:12), <anonymous>:593:9)
    at CompiledProtodef.read (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/compiler.js:70:12)
    at /snapshot/mcsleepingserverstarter/node_modules/protodef/src/compiler.js:111:49
    at tryCatch (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/utils.js:50:16)

**Comment by vincss** [comment]
HI !
Happy to see that the issue is solved, can you tell us the fix that was applied ? You had to set the version in the setting file ?
