### ISSUE TITLE
Version bug

### ISSUE THREAD

**Issue by WarrioR151** [vincss/mcsleepingserverstarter#147]
Hello, when user have for example server on 1.8.8, or whatever version, in server list it shows cross and 1.19.3, also, when user try to connect server from 1.8.8, server wont turn on, get error in console

PartialReadError: Read error for undefined : undefined
    at new ExtendableError (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/utils.js:63:13)
    at new PartialReadError (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/utils.js:70:5)
    at Object.readBool [as bool] (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/datatypes/utils.js:133:41)
    at eval (eval at compile (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/compiler.js:258:12), <anonymous>:606:29)
    at Object.packet_login_start (eval at compile (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/compiler.js:258:12), <anonymous>:612:9)
    at eval (eval at compile (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/compiler.js:258:12), <anonymous>:654:62)
    at packet (eval at compile (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/compiler.js:258:12), <anonymous>:659:9)
    at CompiledProtodef.read (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/compiler.js:70:12)
    at e.message (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/compiler.js:111:49)
    at tryCatch (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/utils.js:50:16)
    
    can it be fixed? Please :/

**Comment by WarrioR151** [comment]
So, to explain.. i have server version 1.8.8, when user look at server list from version 1.8.8, server say (at right, red colored 1.19.3 with X on ping) when user tryes to join, he get the error above in their console, and server don't turn on, when he join server from 1.19.3, the server get started, and when server is started, use is kicked for bad version (because version is 1.8.8) can this be fixed? so when user have server on 1.8.8 the protocol will be on 1.8.8, when he have 1.7.10, protocol will be on 1.7.10 and so on? Like now, it seems it's just 1.19.3  

(also when refreshed server list on version 1.8.8 i got A Prince has taken a quick peek. [1.19.3_::ffff:91.xxxxxxx] in console, but actually.. client was 1.8.8, not 1.19.3

**Comment by vincss** [comment]
Did you try to set the version with the settings : version ?
https://github.com/vincss/mcsleepingserverstarter#%EF%B8%8F-settings

**Comment by WarrioR151** [comment]
Thank you so much, works
