### ISSUE TITLE
Incompatible with ViaBackwards

### ISSUE THREAD

**Issue by william64644** [vincss/mcsleepingserverstarter#149]
[ViaBackwards](https://www.spigotmc.org/resources/viabackwards.27448/) is a plugin that allows clients with an older minecraft versions to join a server with a newer version.

After performing a test to initiate the server automatically using your plugin [mcsleepingserverstarter](https://github.com/vincss/mcsleepingserverstarter) using minecraft 1.9 or 1.12.2, the server console displayed the following output:

    PartialReadError: Read error for undefined : undefined
    at new ExtendableError (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/utils.js:63:13)
    at new PartialReadError (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/utils.js:70:5)
    at Object.readBool [as bool] (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/datatypes/utils.js:133:41)
    at eval (eval at compile (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/compiler.js:258:12), <anonymous>:606:29)
    at Object.packet_login_start (eval at compile (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/compiler.js:258:12), <anonymous>:612:9)
    at eval (eval at compile (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/compiler.js:258:12), <anonymous>:654:62)
    at packet (eval at compile (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/compiler.js:258:12), <anonymous>:659:9)
    at CompiledProtodef.read (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/compiler.js:70:12)
    at /snapshot/mcsleepingserverstarter/node_modules/protodef/src/compiler.js:111:49
    at tryCatch (/snapshot/mcsleepingserverstarter/node_modules/protodef/src/utils.js:50:16)

* [ViaBackwards](https://www.spigotmc.org/resources/viabackwards.27448/) is designed to allow clients from version 1.9 up to the latest version 1.19.3, and it was functioning properly in that regard.
* Everything worked without errors after manually starting the server
* The server uses 1.19.3-417 [PaperMC](https://papermc.io/)

**Comment by vincss** [comment]
Hi !
Thanks for the suggestion, but I don't think the underlaying library support it : 
https://github.com/PrismarineJS/node-minecraft-protocol

**Comment by william64644** [comment]
Looks like it does: 

![image](https://user-images.githubusercontent.com/59394187/220876306-787e6c88-7d49-4f15-a4a9-bc742535b2fb.png)


just go to your mc.createServer and set version to false

**Comment by vincss** [comment]
Thanks for the information, I didn't see that, I will have a look when I have some spare time.

**Comment by william64644** [comment]
I'm sorry for my last report, my recent tests showed that actually no code needs to be changed, just needed to add a line at sleepingSettings.yml containing "version: false". but still, it is a very good idea to add a comment about this somewhere in the config file.
I think we may close this issue now 👍

**Comment by vincss** [comment]
Thanks for the information, great news, I will update the doc.
So keep it open until then.

**Comment by vincss** [comment]
Doc updated
