### ISSUE TITLE
[1.20.4+] Not compatible - Getting Error on Start

### ISSUE THREAD

**Issue by SkyKingPX** [vincss/mcsleepingserverstarter#200]
Hello,
since now I am getting this error when I join instead of the Message, that the Server is starting now:
![image](https://github.com/vincss/mcsleepingserverstarter/assets/95442431/19c9e1e0-0f88-496d-a2ba-ab11287bbf1d)

(But the Server is still starting!)

**Comment by vincss** [comment]
Hi,
Which versions are you using ?
What did you changed since it was working ?

**Comment by SkyKingPX** [comment]
I used the last version of the starter and a snapshot for Spigot 1.20.2

**Comment by vincss** [comment]
I didn't know there was a new version, but I guess it's not compatible with https://github.com/PrismarineJS/node-minecraft-protocol

**Comment by SkyKingPX** [comment]
Oh yes :(

**Comment by SkyKingPX** [comment]
Btw can you do something when JSPrismarine doesn’t update?

**Comment by SkyKingPX** [comment]
@vincss

**Comment by Arthessia** [comment]
Hi,

I've a similar issue, 

`PartialReadError: Read error for undefined : undefined
    at new ExtendableError (/usr/src/myapp/node_modules/protodef/src/utils.js:63:13)
    at new PartialReadError (/usr/src/myapp/node_modules/protodef/src/utils.js:70:5)
    at Object.readVarInt [as varint] (/usr/src/myapp/node_modules/protodef/src/datatypes/utils.js:69:45)
    at Object.packet_message_acknowledgement (eval at compile (/usr/src/myapp/node_modules/protodef/src/compiler.js:258:12), <anonymous>:739:59)
    at eval (eval at compile (/usr/src/myapp/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1117:86)
    at packet (eval at compile (/usr/src/myapp/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1167:9)
    at CompiledProtodef.read (/usr/src/myapp/node_modules/protodef/src/compiler.js:70:12)
    at e.message (/usr/src/myapp/node_modules/protodef/src/compiler.js:111:49)
    at tryCatch (/usr/src/myapp/node_modules/protodef/src/utils.js:50:16)
    at CompiledProtodef.parsePacketBuffer (/usr/src/myapp/node_modules/protodef/src/compiler.js:111:29)`

But... after that error, my server is starting... lol

the only bad thing is : the players on my server are seeing the same issue shared on the screen.

How fix it?

Thanks

**Comment by SkyKingPX** [comment]
My Server is starting too. Only the Message isn’t working.

**Comment by Arthessia** [comment]
Ok after reading all history, it seems we are waiting a PR (https://github.com/PrismarineJS/node-minecraft-protocol/issues/1258)

unfortunatly I'm not really good on JS... I can't really help

**Comment by SkyKingPX** [comment]
Yes, he said this many times, but it just doesn’t update

**Comment by SkyKingPX** [comment]
@vincss Same error with 1.20.4

**Comment by Flothoger** [comment]
Fyi PrismarineJS/node-minecraft-protocol/issues/1258 is now closed.

The new release https://github.com/PrismarineJS/node-minecraft-protocol/releases/tag/1.45.0 is working with 1.20.2.

**Comment by vincss** [comment]
> Fyi [PrismarineJS/node-minecraft-protocol/issues/1258](https://github.com/PrismarineJS/node-minecraft-protocol/issues/1258) is now closed.
> 
> The new release https://github.com/PrismarineJS/node-minecraft-protocol/releases/tag/1.45.0 is working with 1.20.2.

Hi !
Thanks for the update, there seems to be an issue with the latest version : https://github.com/PrismarineJS/node-minecraft-protocol/issues/1255#issuecomment-1870932814

**Comment by vincss** [comment]
A new release has been made for 1.20.2, but still not fully compatible with 1.20.4
https://github.com/vincss/mcsleepingserverstarter/releases

**Comment by SkyKingPX** [comment]
Yeah now its this error for 1.20.4 (I know that is "still not fully compatible")
![image](https://github.com/vincss/mcsleepingserverstarter/assets/95442431/5db2210b-b39c-4619-9cdf-b8f92e2e3c87)
