### ISSUE TITLE
[Request] Server Restart

### ISSUE THREAD

**Issue by SkyKingPX** [vincss/mcsleepingserverstarter#211]
Hello,
it is really annoying that you can’t restart the Server, so please add something…

I even tried using normal batch commands, but even that didn’t work.

an option in the Web-GUI would be also nice 👍

**Comment by vincss** [comment]
Hi,
What do you want to restart ? The minecraft server or the mcsleepingserverstarter ?

**Comment by SkyKingPX** [comment]
Exactly. Because if I make a normal Restart script it no longer launches your sleeper.

**Comment by NoobisJ** [comment]
just do shutdown automatically plugin https://github.com/vincss/mcEmptyServerStopper/releases/tag/v1.1.0

**Comment by SkyKingPX** [comment]
@NoobisJ I meant restart and not stop. Some plugins and I want to restart the server and I don’t want the server to stop.

**Comment by NoobisJ** [comment]
Well there will need to be a restart mod jar file like the empty server stopper. If u find one then u can prob do that other some plug-in if I. Can get the plug-in folder

**Comment by SkyKingPX** [comment]
@NoobisJ What do you mean with:
 If u find one then u can prob do that other some plug-in if you Can get the plug-in folder

**Comment by SkyKingPX** [comment]
Can you do this @vincss ?

**Comment by vincss** [comment]
Yes, but it seems very specific for you, I don't see the point once your server is setup.

**Comment by SkyKingPX** [comment]
@vincss for Spigot there is a restart command and for example I have a Plugin, that updates Geyser and restarts the server after that. But it can’t really do this, because there is no specific script for the starter and so it just shuts down the server, which is a pain

**Comment by SkyKingPX** [comment]
Hello @vincss,
When do you think you'll be done?

**Comment by vincss** [comment]
When I will decide to do it.
You want a button or a command line instruction or something else ?

**Comment by vincss** [comment]
I don't understand: 
"A Command Line for the spigot.yml" 
The config file is loaded when the minecraft server restarts, no ?

**Comment by SkyKingPX** [comment]
@vincss 
In the spigot.yml you can define the Restart script (file) or the command line. I need a command line (or a file) that automatically starts the server with the sleeper, because if I just open the sleeper with the restart command the first one gets an error and on the second window the server starts to sleep again instead of starting.

**Comment by vincss** [comment]
Hi,
I added a button in the web-gui to restart the minecraft server : 
https://github.com/vincss/mcsleepingserverstarter/pull/214

The binary : 
https://github.com/vincss/mcsleepingserverstarter/actions/runs/6995073810

Tells me if it does what you needed.
Don't forget to un-comment the line : # webAllowRestart: true

**Comment by SkyKingPX** [comment]
I can try it tomorrow

**Comment by SkyKingPX** [comment]
@vincss Yes it works fine, but I also need a restart script, because plugins use a restart script (which is normally the script for the server start) which doesn't work with the starter because there is no specific one.

**Comment by vincss** [comment]
Honestly, your request is not very clear, can you give an example ?

You want another command parameter in the setting file ( sleepingSettings.yml ) to use when a server restart is asked ?

**Comment by SkyKingPX** [comment]
No @vincss .
I can explain this:
A spigot server generates a spigot.yml, where you can also set the restart line/script:
![image](https://github.com/vincss/mcsleepingserverstarter/assets/95442431/26a393dd-099b-44cc-b32e-4e530e914e33)
As you can see, you can set this to a script location or the script itself (<- Like in the start.bat)

My problem is, that Plugins like [GeyserUpdater](https://github.com/kejonaMC/GeyserUpdater) ([Config.yml](https://github.com/kejonaMC/GeyserUpdater/blob/main/src/main/resources/config.yml)) to restart the server and the mcsleepingserverstarter does not support a restart from such command line. And because of this the server just shuts down with the message "Restart Script ./start.sh not found. Stopping" without restarting.

This is a problem for me, because Geyser is updating nearly every 2 weeks and the server just randomly shuts down.

I need something like the command "start cmd.exe /c <command>" for Cmd, that opens cmd and runs a command (in this case "quit") that I can put in the restart-script setting in the spigot.yml.

Also it is important to mention, that if you use this setting in the spigot.yml with the normal start.bat (or .sh), it will open a new window and run the server on that one, while the other one closes or stays there if "pause" was put in the .bat/.sh

**Comment by vincss** [comment]
Okayyy !
Thanks clearer now. :-) 

So you can trigger a restart via a command line trough the web api using curl or wget : 
`curl --request POST http://localhost:8080/restart`
or
`wget --post-data "" http://localhost:8080/restart`

You can put this command into a regular .bat file if needed.

**Comment by SkyKingPX** [comment]
thanks, I will test it right now!

**Comment by SkyKingPX** [comment]
@vincss how to use minecraftAutostart and restartDelay ?

**Comment by vincss** [comment]
Add them or uncomment them in the setting file, description is available there as always : 
https://github.com/vincss/mcsleepingserverstarter/tree/feature/add_restart#%EF%B8%8F-settings

**Comment by SkyKingPX** [comment]
@vincss I have another problem now.
When the server is running I need OVER 10 SECONDS to type a SINGLE character! Why??? When the Server is stopped I can normally type "quit"

**Comment by SkyKingPX** [comment]
@vincss The first time I can type normally but when I press enter the ">" isn't there anymore, the command doesn't get send and after that I can't type normally anymore like I said above

**Comment by vincss** [comment]
Because you're on Windows and stream redirection and signals in console are not working well.
That's why I put the "Not killing server:win32, signals are not working well on Windows" message.

If you enter the caractere twice it doesn't work ?

It's not a chat, try not to add a comment every minute, just edit your previous post.

**Comment by SkyKingPX** [comment]
> If you enter the caractere twice it doesn't work ?

No, I have to type it several times. Like 4-8 times.

> It's not a chat, try not to add a comment every minute, just edit your previous post.

Ok, sorry

**Comment by SkyKingPX** [comment]
I use this restart script now, so it closes after it sent the „ping“:

```
@echo off
curl —request POST http://localhost:25566/restart
exit
```

**Comment by vincss** [comment]
If you think it can help other trying to achieve what you have done.

You can run the servers under wsl if you want to avoid some issues linked to Windows 
https://learn.microsoft.com/fr-fr/windows/wsl/install

**Comment by SkyKingPX** [comment]
Hello @vincss ,
I think the server just crashes after the restart packet because there is no shutdown log. And because of crashes I already lost my inventory one time...

**Comment by vincss** [comment]
Indeed, the kill on Windows stop the process immediately.

I changed a bit the way I/O are handled and the stop made on Windows, you can give it a try and tell me if it works for you:
https://github.com/vincss/mcsleepingserverstarter/actions/runs/7172393837

**Comment by SkyKingPX** [comment]
@vincss , yes the stopping/restarting works fine now, but now the commands that I want to send don't get send to the server...

**Comment by vincss** [comment]
Yes we cannot have it all :-D 
That's why I recommend to use WSL for better signal handling.

**Comment by SkyKingPX** [comment]
@vincss Isn‘t there a fix for this without WSL? And could you please explain what the problem is?

**Comment by vincss** [comment]
https://nodejs.org/api/process.html#signal-events

**Comment by SkyKingPX** [comment]
Thanks, but how can I move everything to or use WSL?
@vincss

**Comment by vincss** [comment]
> https://learn.microsoft.com/fr-fr/windows/wsl/install

**Comment by SkyKingPX** [comment]
@vincss I installed it but what now? (I never used Linux 😅)

![image](https://github.com/vincss/mcsleepingserverstarter/assets/95442431/fc3b2fb3-f030-4ae6-bc4c-c7b76486ac4b)

**Comment by vincss** [comment]
Use Google and Learn :-)

Quick tips
You can go to your WSL drive trough the explorer : 
\\wsl.localhost\Ubuntu\home\antony
or 
![image](https://github.com/vincss/mcsleepingserverstarter/assets/2254806/c4ba1162-ca71-430a-9715-4eb5fbfc66b5)

Don't forget to : 
On Linux, try chmod +x mcsleepingserverstarter-linux-x64 if you can't run the executable

You will also need to install java : 
https://docs.papermc.io/misc/java-install

Have fun !

**Comment by SkyKingPX** [comment]
@vincss and then I have to move all servers to that drive to access them?

**Comment by SkyKingPX** [comment]
@vincss can I also install this one? 

https://askubuntu.com/questions/1157417/install-adoptopenjdk-adoptium-onto-ubuntu

**Comment by vincss** [comment]
You have to install at least version 17 : 
https://docs.papermc.io/paper/getting-started

Try to do search by yourself with trials and errors, you don't risk anything. ;-)

**Comment by SkyKingPX** [comment]
@vincss ?

**Comment by vincss** [comment]
It depends what you want to do. Maybe put the whole stuff in WSL would be easier but you have to re-write your script for Linux.

**Comment by SkyKingPX** [comment]
@vincss I already did that, but I don’t know what the command for the restart signal is and how I can run the starter.

**Comment by vincss** [comment]
You just have to make it executable and run it : 
chmod +x mcsleepingserverstarter-linux-x64
./mcsleepingserverstarter-linux-x64

and for the restart it is the same than Windows :
curl --request POST http://localhost:8080/restart
or
wget --post-data "" http://localhost:8080/restart

Only script in linux are bash files with .sh extension.
You can run a bash either by running the sh command with the script as parameter: 
sh restart.sh
or make it executable ans launch it as an executable : 
chmod +x restart.sh
./restart.sh

**Comment by SkyKingPX** [comment]
@vincss I get this error on "quit":
>2023-12-19 14:14:45 info: ----------- [v1.9.0] Starting Minecraft : .start.sh -----------
>2023-12-19 14:14:45 warn: [Main] Caught uncaughtException: "spawn .start.sh ENOENT"
>2023-12-19 14:14:45 error: [Main] Something bad happened
My start.sh contains:
>sudo java -Xms28G -Xmx30G -jar server.jar nogui
(Because I saw this in a tutorial) (I have 32GB RAM)
When I try to run the Command itself, then I got the error, that I have too less RAM, which isn't the case and now I get this:
>Error: Unable to access jarfile server.jar

and I can't connect to the Webserver or through Minecraft. I tried Port forwarding with "sudo ufw allow 25565" (and the other ports) , but it doesn't seem to work.

**Comment by SkyKingPX** [comment]
@vincss 

>2023-12-20 15:56:00 info: [Container] Cleaning up the place.
>2023-12-20 15:56:00 info: [McJava] Closing
>2023-12-20 15:56:00 info: [McJava] Closed
>2023-12-20 15:56:00 info: [BedRock] Closing
>2023-12-20 15:56:00 info: [BedRock] Socket Closed
>2023-12-20 15:56:00 info: ----------- [v1.9.0] Starting Minecraft : java -Xms28G -Xmx30G -jar server.jar nogui -----------
>OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000080000000, 30064771072, 0) failed; error='Not >enough space' (errno=12)
>#
># There is insufficient memory for the Java Runtime Environment to continue.
># Native memory allocation (mmap) failed to map 30064771072 bytes for committing reserved memory.
># An error report file with more information is saved as:
># /opt/Memoria/hs_err_pid532.log
>2023-12-20 15:56:00 info: ----------- [v1.9.0] Minecraft stopped 1 -----------

[hs_err_pid532.log](https://github.com/vincss/mcsleepingserverstarter/files/13728783/hs_err_pid532.log)

I see the problem, but I do not know how to fix it...

**Comment by SkyKingPX** [comment]
@vincss I only removed sudo from the script

**Comment by vincss** [comment]
The error message says that you run out of memory. Because by default, WSL don't use all the memory from your computer : 
https://www.aleksandrhovhannisyan.com/blog/limiting-memory-usage-in-wsl-2/
https://fizzylogic.nl/2023/01/05/how-to-configure-memory-limits-in-wsl2

So you can run the server by removing "-Xms28G -Xmx30G" or change the memory limitation like in the article above :
java -jar server.jar nogui

**Comment by SkyKingPX** [comment]
@vincss the server is starting now, but I get this error:

`
2023-12-22 11:39:09,951 ServerMain ERROR Cannot access RandomAccessFile java.io.FileNotFoundException: logs/latest.log (Permission denied) java.io.FileNotFoundException: logs/latest.log (Permission denied)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:346)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:260)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:128)
        at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager$RollingRandomAccessFileManagerFactory.createManager(RollingRandomAccessFileManager.java:232)
        at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager$RollingRandomAccessFileManagerFactory.createManager(RollingRandomAccessFileManager.java:204)
        at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:144)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:100)
        at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager.getRollingRandomAccessFileManager(RollingRandomAccessFileManager.java:107)
        at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender$Builder.build(RollingRandomAccessFileAppender.java:132)
        at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender$Builder.build(RollingRandomAccessFileAppender.java:53)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:124)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1138)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1063)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1055)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:664)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:258)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:304)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:621)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:694)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:711)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:137)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:61)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:33)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:391)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:416)
        at com.mojang.logging.LogUtils.getLogger(LogUtils.java:62)
        at net.minecraft.server.Main.<clinit>(Main.java:76)
        at org.bukkit.craftbukkit.Main.main(Main.java:325)
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42)
        at java.base/java.lang.Thread.run(Thread.java:1589)

2023-12-22 11:39:09,958 ServerMain ERROR Could not create plugin of type class org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender for element RollingRandomAccessFile: java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager$RollingRandomAccessFileManagerFactory@9f9034a] unable to create manager for [logs/latest.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager$FactoryData@7e531119] java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager$RollingRandomAccessFileManagerFactory@9f9034a] unable to create manager for [logs/latest.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager$FactoryData@7e531119]
        at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:146)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:100)
        at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager.getRollingRandomAccessFileManager(RollingRandomAccessFileManager.java:107)
        at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender$Builder.build(RollingRandomAccessFileAppender.java:132)
        at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender$Builder.build(RollingRandomAccessFileAppender.java:53)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:124)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1138)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1063)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1055)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:664)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:258)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:304)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:621)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:694)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:711)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:137)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:61)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:33)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:391)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:416)
        at com.mojang.logging.LogUtils.getLogger(LogUtils.java:62)
        at net.minecraft.server.Main.<clinit>(Main.java:76)
        at org.bukkit.craftbukkit.Main.main(Main.java:325)
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42)
        at java.base/java.lang.Thread.run(Thread.java:1589)

2023-12-22 11:39:09,961 ServerMain ERROR Unable to invoke factory method in class org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender for element RollingRandomAccessFile: java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:260)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:136)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1138)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1063)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1055)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:664)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:258)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:304)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:621)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:694)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:711)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:137)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:61)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:33)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:391)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:416)
        at com.mojang.logging.LogUtils.getLogger(LogUtils.java:62)
        at net.minecraft.server.Main.<clinit>(Main.java:76)
        at org.bukkit.craftbukkit.Main.main(Main.java:325)
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42)
        at java.base/java.lang.Thread.run(Thread.java:1589)

2023-12-22 11:39:10,009 ServerMain ERROR Null object returned for RollingRandomAccessFile in Appenders.
2023-12-22 11:39:10,025 ServerMain ERROR Appender File cannot be located. Reference ignored
`

**Comment by vincss** [comment]
You should be running your server from a sub folder of your home directory, you can check your current directory with the pwd command, it should be something like : 
/home/anthony/minecraft/server

**Comment by SkyKingPX** [comment]
Ok, because I moved the Server to /opt/

**Comment by SkyKingPX** [comment]
@vincss 
> Try to connect from localhost on the same computer first.

Localhost does work, but not the IP:PORT

**Comment by vincss** [comment]
https://jwstanly.com/blog/article/Port+Forwarding+WSL+2+to+Your+LAN/

**Comment by SkyKingPX** [comment]
@vincss Still same errors and I can’t connect to the Server.

**Comment by SkyKingPX** [comment]
@vincss and I need to do everything again because the UEFI of my cloned drive corrupted...

**Comment by vincss** [comment]
Very sad indeed. But still not related to this piece of software.

**Comment by SkyKingPX** [comment]
I will not use WSL anymore, because of too many problems.
