### ISSUE TITLE
Error (NOT critical, and it does not affect me or my friends.)

### ISSUE THREAD

**Issue by DivannKokos** [vincss/mcsleepingserverstarter#231]
So, I get these on occasion:
```
2024-02-24 22:29:27 info: A Prince has taken a quick peek. [1.20.2_::ffff:94.232.XX.XXX]
PartialReadError: Read error for undefined : Missing characters in string, found size is 3 expected size was 50
    at new ExtendableError (C:\snapshot\mcsleepingserverstarter\node_modules\protodef\src\utils.js:63:13)
    at new PartialReadError (C:\snapshot\mcsleepingserverstarter\node_modules\protodef\src\utils.js:70:5)
    at Object.string (eval at compile (C:\snapshot\mcsleepingserverstarter\node_modules\protodef\src\compiler.js:258:12), <anonymous>:91:15)
    at Object.packet_set_protocol (eval at compile (C:\snapshot\mcsleepingserverstarter\node_modules\protodef\src\compiler.js:258:12), <anonymous>:712:69)
    at eval (eval at compile (C:\snapshot\mcsleepingserverstarter\node_modules\protodef\src\compiler.js:258:12), <anonymous>:728:64)
    at packet (eval at compile (C:\snapshot\mcsleepingserverstarter\node_modules\protodef\src\compiler.js:258:12), <anonymous>:732:9)
    at CompiledProtodef.read (C:\snapshot\mcsleepingserverstarter\node_modules\protodef\src\compiler.js:70:12)
    at C:\snapshot\mcsleepingserverstarter\node_modules\protodef\src\compiler.js:111:49
    at tryCatch (C:\snapshot\mcsleepingserverstarter\node_modules\protodef\src\utils.js:50:16)
    at CompiledProtodef.parsePacketBuffer (C:\snapshot\mcsleepingserverstarter\node_modules\protodef\src\compiler.js:111:29)
Chunk size is 42 but only 2 was read ; partial packet : {"name":96}; buffer :e00000000000436f6f6b69653a206d737473686173683d41646d696e697374720d0a0100080003000000
SleepingMcJava.errorHandler:  Client {
  _events: [Object: null prototype] {
    end: [
      [Function (anonymous)],
      [Function (anonymous)],
      [Function (anonymous)]
    ],
    set_protocol: [Function: bound onceWrapper] { listener: [Function: onHandshake] },
    state: [Function (anonymous)],
    error: [Function (anonymous)],
    login_start: [Function: bound onceWrapper] { listener: [Function: onLogin] },
    ping_start: [Function: bound onceWrapper] { listener: [Function: onPing] },
    legacy_server_list_ping: [Function: bound onceWrapper] { listener: [Function: onLegacyPing] }
  },
  _eventsCount: 7,
  _maxListeners: undefined,
  customPackets: undefined,
  version: '1.20.2',
  isServer: true,
  splitter: Splitter {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: {},
      length: 0,
      pipes: [Array],
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      constructed: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      destroyed: false,
      errored: null,
      closed: false,
      closeEmitted: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      prefinish: [Function: prefinish],
      end: [Function],
      data: [Function: ondata],
      error: [Array],
      unpipe: [Function: onunpipe],
      close: [Function],
      finish: [Function]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    allowHalfOpen: true,
    buffer: <Buffer >,
    recognizeLegacyPing: true,
    [Symbol(kCapture)]: false,
    [Symbol(kCallback)]: null
  },
  packetsToParse: {},
  compressor: null,
  framer: Framer {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: {},
      length: 0,
      pipes: [],
      flowing: false,
      ended: true,
      endEmitted: true,
      reading: false,
      constructed: true,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      destroyed: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: false,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: true
    },
    _events: [Object: null prototype] {
      prefinish: [Function: prefinish],
      error: [Function: onError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: true,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: true,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: true,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      [Symbol(kOnFinished)]: []
    },
    allowHalfOpen: true,
    [Symbol(kCapture)]: false,
    [Symbol(kCallback)]: null
  },
  cipher: null,
  decipher: null,
  decompressor: null,
  ended: false,
  latency: 0,
  hideErrors: false,
  closeTimer: Timeout {
    _idleTimeout: 30000,
    _idlePrev: [TimersList],
    _idleNext: [TimersList],
    _idleStart: 21535566,
    _onTimeout: [Function: bound destroy],
    _timerArgs: undefined,
    _repeat: null,
    _destroyed: false,
    [Symbol(refed)]: true,
    [Symbol(kHasPrimitive)]: false,
    [Symbol(asyncId)]: 3130,
    [Symbol(triggerId)]: 3113
  },
  protocolState: 'handshaking',
  serializer: Serializer {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: false,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      paused: false,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: false,
    _events: [Object: null prototype] {
      prefinish: [Function: prefinish],
      error: [Function (anonymous)]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: true,
      highWaterMark: 16,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function (anonymous)],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [CorkedRequest]
    },
    writable: false,
    allowHalfOpen: true,
    _transformState: {
      afterTransform: [Function: bound afterTransform],
      needTransform: false,
      transforming: false,
      writecb: null,
      writechunk: null,
      writeencoding: null
    },
    proto: CompiledProtodef {
      sizeOfCtx: [Object],
      writeCtx: [Object],
      readCtx: [Object]
    },
    mainType: 'packet',
    queue: <Buffer >,
    [Symbol(kCapture)]: false
  },
  deserializer: FullPacketParser {
    _readableState: ReadableState {
      objectMode: true,
      highWaterMark: 16,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      paused: false,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] {
      prefinish: [Function: prefinish],
      error: [Array],
      data: [Function (anonymous)],
      unpipe: [Function: onunpipe],
      close: [Function],
      finish: [Function]
    },
    _eventsCount: 6,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function (anonymous)],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [CorkedRequest]
    },
    writable: true,
    allowHalfOpen: true,
    _transformState: {
      afterTransform: [Function: bound afterTransform],
      needTransform: true,
      transforming: false,
      writecb: null,
      writechunk: null,
      writeencoding: 'buffer'
    },
    proto: CompiledProtodef {
      sizeOfCtx: [Object],
      writeCtx: [Object],
      readCtx: [Object]
    },
    mainType: 'packet',
    noErrorLogging: false,
    [Symbol(kCapture)]: false
  },
  _mcBundle: [],
  _hasBundlePacket: true,
  _end: [Function: end],
  end: [Function: end],
  id: 0,
  socket: Socket {
    connecting: false,
    _hadError: false,
    _parent: null,
    _host: null,
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [Array],
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      constructed: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: true,
      emitClose: false,
      autoDestroy: true,
      destroyed: true,
      errored: [Error],
      closed: true,
      closeEmitted: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      end: [Array],
      connect: [Function (anonymous)],
      error: [Function: onFatalError],
      close: [Function: endSocket],
      timeout: [Function: endSocket],
      data: [Function: ondata]
    },
    _eventsCount: 6,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: true,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: true,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: true,
      errorEmitted: true,
      emitClose: false,
      autoDestroy: true,
      errored: [Error],
      closed: true,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    allowHalfOpen: false,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server: Server {
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      _connections: 0,
      _handle: [TCP],
      _usingWorkers: false,
      _workers: [],
      _unref: false,
      allowHalfOpen: false,
      pauseOnConnect: false,
      noDelay: false,
      keepAlive: false,
      keepAliveInitialDelay: 0,
      _connectionKey: '6::::20365',
      [Symbol(kCapture)]: false,
      [Symbol(async_id_symbol)]: 3087
    },
    _server: Server {
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      _connections: 0,
      _handle: [TCP],
      _usingWorkers: false,
      _workers: [],
      _unref: false,
      allowHalfOpen: false,
      pauseOnConnect: false,
      noDelay: false,
      keepAlive: false,
      keepAliveInitialDelay: 0,
      _connectionKey: '6::::20365',
      [Symbol(kCapture)]: false,
      [Symbol(async_id_symbol)]: 3087
    },
    _peername: { address: '::ffff:94.232.XX.XXX', family: 'IPv6', port: 65222 },
    [Symbol(async_id_symbol)]: 3107,
    [Symbol(kHandle)]: null,
    [Symbol(lastWriteQueueSize)]: 0,
    [Symbol(timeout)]: null,
    [Symbol(kBuffer)]: null,
    [Symbol(kBufferCb)]: null,
    [Symbol(kBufferGen)]: null,
    [Symbol(kCapture)]: false,
    [Symbol(kSetNoDelay)]: true,
    [Symbol(kSetKeepAlive)]: false,
    [Symbol(kSetKeepAliveInitialDelay)]: 0,
    [Symbol(kBytesRead)]: 47,
    [Symbol(kBytesWritten)]: 0
  },
  _endReason: 'LoginTimeout',
  [Symbol(kCapture)]: false
} Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
```
It does not actually affect me or my friends in any way (IP is not mine or any of my friends, and we connect fine), nor it does bother me, but just letting you know.
I edited last numbers of ip, just in case.
Whitelist on (both here and on server) and rcon off, if it matters.

**Comment by DivannKokos** [comment]
also why it writes C:\snapshot\mcsleepingserverstarter
i have it in other folder on the other drive

**Comment by vincss** [comment]
For your first issue, it's probably someone with a strange client.

The second one is a side effect from using pkg (https://github.com/vercel/pkg) to build the binary package.
