### ISSUE TITLE
Web GUI does not successfully stop server

### ISSUE THREAD

**Issue by chrisnair** [vincss/mcsleepingserverstarter#259]
paper server 1.20.2 on ubuntu (let me know if you need more environment info)

Upon pressing web gui sleep button, I get the following console output:
Note `Minecraft stopped null` (weird that it's null)
```
> 2024-09-13 05:02:08 info: [WebServer](::ffff:192.168.1.83) Stopping server was Running
2024-09-13 05:02:08 info: ----------- [v1.9.1] Minecraft stopped null -----------
2024-09-13 05:02:08 info: [Container] ...Time to kill me if you want (5 secs)...
2024-09-13 05:02:13 info: Retrieved settings:{"serverName":"VANILLA","serverPort":25565,"maxPlayers":20,"loginMessage":"...Waking server up, come back in a minute...","serverOnlineMode":true,"startMinecraft":true,"minecraftCommand":"sh start.sh","restartDelay":5000,"version":false,"useWhitelistFile":false,"useBlacklistFiles":false,"useNativeFiles":false,"serverMOTD":"(Vanilla) Your Minecraft version must be 1.20.2 to awaken the server.","webPort":5352}
2024-09-13 05:02:13 info: Retrieving whitelist entries from /mnt/ssd/minecraft_server/whitelist.json
2024-09-13 05:02:13 info: Retrieved whitelist entries:[]
2024-09-13 05:02:13 info: Retrieving banned ips from /mnt/ssd/minecraft_server/banned-ips.json
2024-09-13 05:02:13 info: Retrieved banned ips:[]
2024-09-13 05:02:13 info: Retrieving banned players from /mnt/ssd/minecraft_server/banned-players.json
2024-09-13 05:02:13 info: Retrieved banned players:[]
2024-09-13 05:02:13 info: [Container] ...Too late !...
2024-09-13 05:02:13 info: [McJava] Waiting for a Prince to come. [25565]
2024-09-13 05:02:13 error: Something went wrong in wonderland listen EADDRINUSE: address already in use :::25565
```
As you can see by EADDRINUSE, the server has not been shut down.
The web GUI will show Sleeping in this case, but if you try to start the server it will throw:
```
[05:05:50 ERROR]: Failed to start the minecraft server
net.minecraft.util.SessionLock$ExceptionWorldConflict: /mnt/ssd/minecraft_server/./world/session.lock: already locked (possibly by other Minecraft instance?)
        at net.minecraft.util.DirectoryLock$LockException.alreadyLocked(DirectoryLock.java:102) ~[?:?]
        at net.minecraft.util.DirectoryLock.create(DirectoryLock.java:30) ~[?:?]
        at net.minecraft.world.level.storage.LevelStorageSource$LevelStorageAccess.<init>(LevelStorageSource.java:538) ~[?:?]
        at net.minecraft.world.level.storage.LevelStorageSource.validateAndCreateAccess(LevelStorageSource.java:451) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:208) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.Main.main(Main.java:325) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```
only if an interrupt is given, the server closes successfully, after the sleeping server starter already believes it has closed.

**Comment by vincss** [comment]
Hi,
Are you sure you don't have another server running ?
Can you pass your config file ?

**Comment by chrisnair** [comment]
Yes, I'm sure there is no other server running. Server configuration is included at the bottom of this comment.
Here are exact steps to reproduce with expected and actual behavior:
1. Execute ./mcsleepingserverstarter
2. Start minecraft server, either by web GUI start button or by attempting to join.
3. Send server to sleep using web GUI

Expected result: 
- Minecraft server shuts down
- SleepingServerStarter begins watching for players joining
- web GUI displays server state as sleeping



Actual result:
```
> 2024-09-13 05:02:08 info: [WebServer](::ffff:192.168.1.83) Stopping server was Running
2024-09-13 05:02:08 info: ----------- [v1.9.1] Minecraft stopped null -----------
2024-09-13 05:02:08 info: [Container] ...Time to kill me if you want (5 secs)...
2024-09-13 05:02:13 info: Retrieved settings:{"serverName":"VANILLA","serverPort":25565,"maxPlayers":20,"loginMessage":"...Waking server up, come back in a minute...","serverOnlineMode":true,"startMinecraft":true,"minecraftCommand":"sh start.sh","restartDelay":5000,"version":false,"useWhitelistFile":false,"useBlacklistFiles":false,"useNativeFiles":false,"serverMOTD":"(Vanilla) Your Minecraft version must be 1.20.2 to awaken the server.","webPort":5352}
2024-09-13 05:02:13 info: Retrieving whitelist entries from /mnt/ssd/minecraft_server/whitelist.json
2024-09-13 05:02:13 info: Retrieved whitelist entries:[]
2024-09-13 05:02:13 info: Retrieving banned ips from /mnt/ssd/minecraft_server/banned-ips.json
2024-09-13 05:02:13 info: Retrieved banned ips:[]
2024-09-13 05:02:13 info: Retrieving banned players from /mnt/ssd/minecraft_server/banned-players.json
2024-09-13 05:02:13 info: Retrieved banned players:[]
2024-09-13 05:02:13 info: [Container] ...Too late !...
2024-09-13 05:02:13 info: [McJava] Waiting for a Prince to come. [25565]
2024-09-13 05:02:13 error: Something went wrong in wonderland listen EADDRINUSE: address already in use :::25565
```

- The above log output, showing that SleepingServerStarter has identified that the Minecraft server has stopped, and that it attempts to connect.
- Web GUI displays the server state as sleeping.
- Inspection of htop verifies minecraft server jar has not stopped running.



# sleepingSettings.YML
```
serverName: VANILLA
serverMOTD: (Vanilla) Your Minecraft version must be 1.20.2 to awaken the server.
serverPort: 25565
maxPlayers: 20
loginMessage: ...Waking server up, come back in a minute...
serverOnlineMode: true
startMinecraft: true
minecraftCommand: sh start.sh
restartDelay: 5000
version: false
useWhitelistFile: false
useBlacklistFiles: false
useNativeFiles: false
webPort: 8672
```
# server.properties
```
#Minecraft server properties
#Sat Sep 14 04:29:21 CST 2024
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings={}
enforce-secure-profile=true
level-name=world
motd=(Vanilla) Your Minecraft version must be 1.20.2 to play.
query.port=25565
pvp=true
generate-structures=true
max-chained-neighbor-updates=1000000
difficulty=easy
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
use-native-transport=true
max-players=20
online-mode=true
enable-status=true
allow-flight=false
initial-disabled-packs=
broadcast-rcon-to-ops=true
view-distance=10
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=25565
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=10
rcon.password=
player-idle-timeout=0
debug=false
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
log-ips=true
function-permission-level=2
initial-enabled-packs=vanilla
level-type=minecraft\:normal
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
spawn-protection=16
resource-pack-sha1=
max-world-size=29999984
```

**Comment by vincss** [comment]
And what's the content of start.sh ?
I don't see why it would fail to stop the server.

**Comment by chrisnair** [comment]
Deleting and reinstalling server and sleepingserver starter seems to have fixed the issue. Unsure what was misconfigured.
