### ISSUE TITLE
Error when running npm start

### ISSUE THREAD

**Issue by Bitslayn** [vincss/mcsleepingserverstarter#97]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.11
3 info using node@v10.24.0
4 verbose config Skipping project config: /home/opc/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle mcsleepingserverstarter@1.1.5~prestart: mcsleepingserverstarter@1.1.5
7 info lifecycle mcsleepingserverstarter@1.1.5~start: mcsleepingserverstarter@1.1.5
8 verbose lifecycle mcsleepingserverstarter@1.1.5~start: unsafe-perm in lifecycle true
9 verbose lifecycle mcsleepingserverstarter@1.1.5~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/opc/node_modules/.bin:/home/opc/.local/bin:/home/opc/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
10 verbose lifecycle mcsleepingserverstarter@1.1.5~start: CWD: /home/opc
11 silly lifecycle mcsleepingserverstarter@1.1.5~start: Args: [ '-c',
11 silly lifecycle   'npm run prebuild && npm run build:typescript && node .' ]
12 silly lifecycle mcsleepingserverstarter@1.1.5~start: Returned: code: 1  signal: null
13 info lifecycle mcsleepingserverstarter@1.1.5~start: Failed to exec start script
14 verbose stack Error: mcsleepingserverstarter@1.1.5 start: `npm run prebuild && npm run build:typescript && node .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14 verbose stack     at EventEmitter.emit (events.js:198:13)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:198:13)
14 verbose stack     at maybeClose (internal/child_process.js:982:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
15 verbose pkgid mcsleepingserverstarter@1.1.5
16 verbose cwd /home/opc
17 verbose Linux 5.4.17-2136.306.1.3.el8uek.aarch64
18 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
19 verbose node v10.24.0
20 verbose npm  v6.14.11
21 error code ELIFECYCLE
22 error errno 1
23 error mcsleepingserverstarter@1.1.5 start: `npm run prebuild && npm run build:typescript && node .`
23 error Exit status 1
24 error Failed at the mcsleepingserverstarter@1.1.5 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by vincss** [comment]
Hi !
You should use newer versions of node & npm :
    "engines": {
        "node": ">=16",
        "npm": ">=8"
    },

How did you run it ? It should warn you before running it.

**Comment by iwa** [comment]
@Bitslayn any news?
as your logs shows, and vincss told you, you need to install a newer version of NodeJS
you're currently on the v10, and you need to be at least on the v16

you can download the latest release on their official website here : https://nodejs.org/en/

please retry with the right version and re-open the issue if you still have a problem 😉
